### ISSUE TITLE
Crashes due to exceeding item size in Dyanamo DB

### ISSUE THREAD

**Issue by davisyoshida** [IrakliZ/annoy-a-ton#1]
Pls

**Comment by EntilZha** [comment]
This issue is extremely important. The software is unusable without it and I demand it is fixed since this is an OSS project and you're the maintainer

**Comment by davisyoshida** [comment]
(っ-̶●̃益●̶̃)っ

**Comment by davisyoshida** [comment]
(ﾉಠдಠ)ﾉ︵┻━┻
